// MOCK DATA for WelB (Thailand-focused)

import type { OnlineProduct, EventModel, DigitalContent } from "@/types";

export const onlineProducts: OnlineProduct[] = [
  {
    id: "1",
    title: "Bitcoin Hardware Wallet Case",
    category: "Accessories",
    price: 50000,
    currency: "SATS",
    sellerName: "Lightning Store TH",
    contactUrl: "https://t.me/lightningstore",
    imageUrl: "",
  },
  {
    id: "2",
    title: "Orange Pill T-Shirt",
    category: "Apparel",
    price: 120000,
    currency: "SATS",
    sellerName: "Bitcoin Merch Co",
    contactUrl: "https://wa.me/1234567890",
    imageUrl: "",
  },
  {
    id: "3",
    title: "Node Runner Hoodie",
    category: "Apparel",
    price: 250000,
    currency: "SATS",
    sellerName: "HODL Fashion",
    contactUrl: "https://t.me/hodlfashion",
    imageUrl: "",
  },
  {
    id: "4",
    title: "Bitcoin Mining Sticker Pack",
    category: "Stickers",
    price: 10000,
    currency: "SATS",
    sellerName: "Stacked Sats Shop",
    contactUrl: "https://wa.me/0987654321",
    imageUrl: "",
  },
  {
    id: "5",
    title: "Lightning Network Mug",
    category: "Accessories",
    price: 35000,
    currency: "SATS",
    sellerName: "Lightning Store TH",
    contactUrl: "https://t.me/lightningstore",
    imageUrl: "",
  },
  {
    id: "6",
    title: "Cold Storage Steel Plate",
    category: "Security",
    price: 500000,
    currency: "SATS",
    sellerName: "Secure Sats",
    contactUrl: "https://t.me/securesats",
    imageUrl: "",
  },
];

export const digitalContent: DigitalContent[] = [
  {
    id: "1",
    title: "Understanding Lightning Network",
    contentType: "Video",
    creatorName: "Adi Pratama",
    category: "Education",
    previewUrl: "",
    externalUrl: "https://youtube.com",
  },
  {
    id: "2",
    title: "The Bitcoin Standard (Notes)",
    contentType: "E-book",
    creatorName: "Rina Sari",
    category: "Books",
    previewUrl: "",
    externalUrl: "https://example.com",
  },
  {
    id: "3",
    title: "Running a Bitcoin Node in 2026",
    contentType: "Slide",
    creatorName: "Budi Crypto",
    category: "Technical",
    previewUrl: "",
    externalUrl: "https://slides.com",
  },
  {
    id: "4",
    title: "Why Bitcoin Matters for Thailand",
    contentType: "Article",
    creatorName: "Somchai BTC",
    category: "Opinion",
    previewUrl: "",
    externalUrl: "https://medium.com",
  },
  {
    id: "5",
    title: "Bitcoin Mining Explained Simply",
    contentType: "Video",
    creatorName: "Dian BTC",
    category: "Education",
    previewUrl: "",
    externalUrl: "https://youtube.com",
  },
  {
    id: "6",
    title: "Self Custody Best Practices",
    contentType: "Article",
    creatorName: "Satoshi TH",
    category: "Security",
    previewUrl: "",
    externalUrl: "https://example.com",
  },
];
