CREATE TABLE "spots" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"description" text NOT NULL,
	"type" varchar(20) DEFAULT 'shop' NOT NULL,
	"category" varchar(255) NOT NULL,
	"region" varchar(255) NOT NULL,
	"province" varchar(100) NOT NULL,
	"province_th" varchar(255),
	"district" varchar(255),
	"district_th" varchar(255),
	"address" text,
	"lat" numeric(10, 8),
	"lng" numeric(11, 8),
	"google_map_link" text NOT NULL,
	"phone" varchar(20),
	"facebook_link" text,
	"website_link" text,
	"is_suggested" boolean DEFAULT false NOT NULL,
	"is_verified" boolean DEFAULT false NOT NULL,
	"is_local_verified" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
