export const categories = [
  "food",
  "accommodation",
  "shopping",
  "services",
  "health",
  "entertainment",
  "transport",
  "community",
  "other",
] as const;

export const subCategories = [
  { subCategory: "cafe", category: "food" },
  { subCategory: "restaurant", category: "food" },
  { subCategory: "bar", category: "food" },
  { subCategory: "bakery", category: "food" },
  { subCategory: "hotel", category: "accommodation" },
  { subCategory: "hostel", category: "accommodation" },
  { subCategory: "resort", category: "accommodation" },
  { subCategory: "electronics", category: "shopping" },
  { subCategory: "fashion", category: "shopping" },
  { subCategory: "grocery", category: "shopping" },
  { subCategory: "retail", category: "shopping" },
  { subCategory: "barber", category: "services" },
  { subCategory: "salon", category: "services" },
  { subCategory: "laundry", category: "services" },
  { subCategory: "repair", category: "services" },
  { subCategory: "pharmacy", category: "health" },
  { subCategory: "clinic", category: "health" },
  { subCategory: "gym", category: "health" },
  { subCategory: "spa", category: "health" },
  { subCategory: "gaming", category: "entertainment" },
  { subCategory: "cinema", category: "entertainment" },
  { subCategory: "bike", category: "transport" },
  { subCategory: "taxi", category: "transport" },
  { subCategory: "coworking", category: "community" },
  { subCategory: "education", category: "community" },
  { subCategory: "community-space", category: "community" },
  { subCategory: "cannabis", category: "other" },
  { subCategory: "pet", category: "other" },
  { subCategory: "art", category: "other" },
  { subCategory: "general", category: "other" },
] as const;
