export const regions = [
  "Bangkok",
  "Huai Phueng",
  "Chiang Mai",
  "Phuket",
  "Yala",
  "Hat Yai",
  "Northern",
  "Northeastern",
  "Central",
  "Eastern",
  "Western",
  "Southern",
] as const;

export const districtToRegion = [
  { district: "Huai Phueng", province: "Kalasin", region: "Huai Phueng" },
  { district: "Hat Yai", province: "Songkhla", region: "Hat Yai" },
] as const;

export const provinceToRegion = [
  { province: "Bangkok", region: "Bangkok" },
  { province: "Chiang Mai", region: "Chiang Mai" },
  { province: "Phuket", region: "Phuket" },
  { province: "Yala", region: "Yala" },
  // Northern
  { province: "Chiang Rai", region: "Northern" },
  { province: "Lampang", region: "Northern" },
  { province: "Lamphun", region: "Northern" },
  { province: "Mae Hong Son", region: "Northern" },
  { province: "Nan", region: "Northern" },
  { province: "Phayao", region: "Northern" },
  { province: "Phrae", region: "Northern" },
  { province: "Uttaradit", region: "Northern" },
  { province: "Sukhothai", region: "Northern" },
  { province: "Tak", region: "Northern" },
  { province: "Kamphaeng Phet", region: "Northern" },
  { province: "Phitsanulok", region: "Northern" },
  { province: "Phichit", region: "Northern" },
  { province: "Phetchabun", region: "Northern" },
  // Northeastern
  { province: "Nakhon Ratchasima", region: "Northeastern" },
  { province: "Khon Kaen", region: "Northeastern" },
  { province: "Udon Thani", region: "Northeastern" },
  { province: "Ubon Ratchathani", region: "Northeastern" },
  { province: "Kalasin", region: "Northeastern" },
  { province: "Chaiyaphum", region: "Northeastern" },
  { province: "Buri Ram", region: "Northeastern" },
  { province: "Surin", region: "Northeastern" },
  { province: "Sisaket", region: "Northeastern" },
  { province: "Roi Et", region: "Northeastern" },
  { province: "Maha Sarakham", region: "Northeastern" },
  { province: "Loei", region: "Northeastern" },
  { province: "Nong Khai", region: "Northeastern" },
  { province: "Nong Bua Lamphu", region: "Northeastern" },
  { province: "Sakon Nakhon", region: "Northeastern" },
  { province: "Nakhon Phanom", region: "Northeastern" },
  { province: "Mukdahan", region: "Northeastern" },
  { province: "Yasothon", region: "Northeastern" },
  { province: "Amnat Charoen", region: "Northeastern" },
  { province: "Bueng Kan", region: "Northeastern" },
  // Central
  { province: "Nonthaburi", region: "Central" },
  { province: "Pathum Thani", region: "Central" },
  { province: "Samut Prakan", region: "Central" },
  { province: "Samut Sakhon", region: "Central" },
  { province: "Samut Songkhram", region: "Central" },
  { province: "Nakhon Pathom", region: "Central" },
  { province: "Ayutthaya", region: "Central" },
  { province: "Ang Thong", region: "Central" },
  { province: "Lopburi", region: "Central" },
  { province: "Sing Buri", region: "Central" },
  { province: "Chainat", region: "Central" },
  { province: "Saraburi", region: "Central" },
  { province: "Nakhon Nayok", region: "Central" },
  { province: "Suphan Buri", region: "Central" },
  { province: "Nakhon Sawan", region: "Central" },
  { province: "Uthai Thani", region: "Central" },
  // Eastern
  { province: "Chon Buri", region: "Eastern" },
  { province: "Rayong", region: "Eastern" },
  { province: "Chanthaburi", region: "Eastern" },
  { province: "Trat", region: "Eastern" },
  { province: "Prachinburi", region: "Eastern" },
  { province: "Sa Kaeo", region: "Eastern" },
  // Western
  { province: "Kanchanaburi", region: "Western" },
  { province: "Ratchaburi", region: "Western" },
  { province: "Phetchaburi", region: "Western" },
  { province: "Prachuap Khiri Khan", region: "Western" },
  // Southern
  { province: "Chumphon", region: "Southern" },
  { province: "Ranong", region: "Southern" },
  { province: "Surat Thani", region: "Southern" },
  { province: "Nakhon Si Thammarat", region: "Southern" },
  { province: "Phatthalung", region: "Southern" },
  { province: "Songkhla", region: "Southern" },
  { province: "Satun", region: "Southern" },
  { province: "Trang", region: "Southern" },
  { province: "Pattani", region: "Southern" },
  { province: "Narathiwat", region: "Southern" },
  { province: "Krabi", region: "Southern" },
  { province: "Phang Nga", region: "Southern" },
] as const;
