-- Seed from welb-activities.txt (WelB portfolio activities)
INSERT INTO events (
  title,
  description,
  spot_id,
  type,
  price,
  currency,
  start_date,
  end_date,
  location,
  organizer_name,
  image_url,
  event_url,
  registration_url,
  participant_count,
  is_welb_project,
  is_market
) VALUES
(
  'SchoolxBitcoin',
  'วันนเด็กปีนี้ เราได้นำเงินโดเนทส่วนหนึ่งจากโปรเจค #bitcoinxschool นำไปซื้อขนมแจกจ่ายน้อง ๆ นักเรียนจำนวน 50 ชิ้น กราบขอบพระคุณแทนน้อง ๆ ด้วยนะคะสำหรับผู้ใจดีทั้งหลาย ฮิฮิ',
  NULL,
  'project',
  NULL,
  NULL,
  '2026-01-01T00:00:00+07:00',
  NULL,
  '',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/611154963_1436440214809304_8450075707627674267_n.jpg',
  NULL,
  NULL,
  NULL,
  true,
  false
),
(
  'BOB Space lightning Market',
  'การร่วมงานกันของ bob sapce และ WelB ในการจัด lightning market อย่างเป็นทางการครั้งแรกที่ bob space เอกมัย และยังมีจัดอย่างต่อเนื่องจนถึงปัจจุบัน ทุกศุกร์สุดท้ายของเดือนเป็นเสมือน monthly event ที่ bob space และ WelB ทำร่วมกันเพื่อ bitcoiner ทุกคน',
  NULL,
  'lightning market',
  NULL,
  NULL,
  '2025-12-01T00:00:00+07:00',
  NULL,
  'BOB Space Ekkamai',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/IMG_6610.png',
  NULL,
  NULL,
  NULL,
  true,
  true
),
(
  'Chit beer 13th Anniversary',
  'ฉลอง 13 ปี Chitbeer เกาะเกร็ด ที่ได้ร่วมเชิญลานกรองมันส์ และ WelB ร่วมขายสินค้ารับ bitcoin ในงาน',
  NULL,
  'lightning market',
  NULL,
  NULL,
  '2025-12-01T00:00:00+07:00',
  NULL,
  'Chitbeer Koh Kret',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/IMG_8633.jpeg',
  NULL,
  NULL,
  NULL,
  true,
  true
),
(
  'สอนเก็บออม bitcoin ระยะยาว',
  'เพื่องสร้างความเข้าใจและการใช้งาน Hardware Wellet อย่างถูกวิธี นี่จึงเป็นคอร์สแรกที่ WelB ได้จัดขึ้น',
  NULL,
  'course',
  NULL,
  NULL,
  '2025-12-01T00:00:00+07:00',
  NULL,
  '',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/IMG_8634.jpeg',
  NULL,
  NULL,
  NULL,
  true,
  false
),
(
  'Bitcoin Half Marathon and Bitcoin Popup village',
  'WelB ได้รับเชิญไปพูดหัวข้อ เมื่อร้านค้ารับ bitcoin และได้มีส่วนร่วมจัด lightning market ในบริเวณ popup village ร่วมกับ BLC และ ลานกรองมันส์',
  NULL,
  'speaker',
  NULL,
  NULL,
  '2025-11-01T00:00:00+07:00',
  NULL,
  'Popup village',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/Screenshot%202025-12-27%20150726.png',
  NULL,
  NULL,
  NULL,
  true,
  false
),
(
  'Bitcoin Future of Money',
  'SWTK ได้เชิญ มายด์ WelB ให้เล่าถึงวิธีการและประสบการณ์ของธุรกิจที่รับชำระด้วย bitcoin และความได้เปรียบ หากธุรกิจของเรารับชำระ bitcoin ก่อนคู่แข่ง',
  NULL,
  'speaker',
  NULL,
  NULL,
  '2025-09-01T00:00:00+07:00',
  NULL,
  '',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/IMG_8639.jpeg',
  NULL,
  NULL,
  NULL,
  true,
  false
),
(
  'Bitcoin Digital and Freedom เชียงใหม่',
  'BLC and SWTK',
  NULL,
  'speaker',
  NULL,
  NULL,
  '2025-08-01T00:00:00+07:00',
  NULL,
  '',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/IMG_8643.jpeg',
  NULL,
  NULL,
  NULL,
  true,
  false
),
(
  'BOB Space Grassroot Adoption',
  'WelB ถูกเทียบเชิญเป็นครั้งแรกจาก BOB space ให้พูดถึงยากลำบากของการใช้งาน bitcoin ในระดับรากหญ้าของคนทั่วไปและธุรกิจ SME ที่รับ bitcoin เพื่อแก้ไขและผลักดันให้ Hyperbitcoinization เกิดขึ้นจริง',
  NULL,
  'lightning market',
  NULL,
  NULL,
  '2025-08-01T00:00:00+07:00',
  NULL,
  'BOB Space',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/IMG_8839%20(1).PNG',
  NULL,
  NULL,
  NULL,
  true,
  true
),
(
  'Paknam101',
  'Paknam101 Meet up ครั้งแรกที่ร้าน Ramita Coffee and Bistro',
  NULL,
  'meetup',
  NULL,
  NULL,
  '2025-04-01T00:00:00+07:00',
  NULL,
  'Ramita Coffee and Bistro',
  'WelB',
  'https://raw.githubusercontent.com/welb21proton-afk/welb-images/main/IMG_8631.png',
  NULL,
  NULL,
  NULL,
  true,
  false
);
